AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: STARK infra for the parser and code generator
Parameters:
    UserCICDPipelineBucketNameParameter:
        Type: String
        Description: Name for user bucket that will be used for the default STARK CI/CD pipeline.
    UserCodeGenBucketNameParameter:
        Type: String
        Description: Name for user bucket that will hold static files and deployment packages created by STARK
    UserWebsiteBucketNameParameter:
        Type: String
        Description: Name for user bucket that will be used as the website bucket for the STARK Parser UI. Not yet used in template, just needed for config.
Resources:
    STARKCloudFormationDeployServiceRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement: 
                    - 
                        Effect: Allow
                        Principal:
                           Service: 
                              - 'cloudformation.amazonaws.com'
                        Action: 'sts:AssumeRole'
            ManagedPolicyArns:
                - 'arn:aws:iam::aws:policy/AdministratorAccess'
    STARKParserApi:
        Type: AWS::Serverless::HttpApi
        Properties:
            CorsConfiguration:
                AllowOrigins:
                    - "*"
                AllowHeaders:
                    - "*"
                AllowMethods:
                    - "*"
                MaxAge: 200
                AllowCredentials: False
    CFCustomResourceHelperLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: !Ref UserCodeGenBucketNameParameter
                S3Key: STARKLambdaLayers/CF_CustomResourceHelper_py39.zip
            Description: Lambda-backed custom resource library for CloudFormation
            LayerName: STARK_CF_CustomResourceHelper
            CompatibleArchitectures:
                - x86_64
                - arm64
            CompatibleRuntimes:
                - python3.6
                - python3.7
                - python3.8
                - python3.9
    PyYamlLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: !Ref UserCodeGenBucketNameParameter
                S3Key: STARKLambdaLayers/yaml_py39.zip
            Description: YAML module for Python 3.x
            LayerName: STARK_PyYAML
            CompatibleArchitectures:
                - x86_64
                - arm64
            CompatibleRuntimes:
                - python3.6
                - python3.7
                - python3.8
                - python3.9
    RequestslLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: !Ref UserCodeGenBucketNameParameter
                S3Key: STARKLambdaLayers/requests_py39.zip
            Description: Requests module for Python 3.x
            LayerName: STARK_Requests
            CompatibleArchitectures:
                - x86_64
                - arm64
            CompatibleRuntimes:
                - python3.6
                - python3.7
                - python3.8
                - python3.9
    PymongoLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: !Ref UserCodeGenBucketNameParameter
                S3Key: STARKLambdaLayers/pymongo_py39.zip
            Description: Pymongo module for Python 3.x
            LayerName: STARK_Pymongo
            CompatibleArchitectures:
                - x86_64
                - arm64
            CompatibleRuntimes:
                - python3.6
                - python3.7
                - python3.8
                - python3.9
    STARKFriendlyToSystemNamesLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: !Ref UserCodeGenBucketNameParameter
                S3Key: STARKLambdaLayers/STARK_friendly_to_system_name_py39.zip
            Description: STARK module for converting user-supplied, human-friendly identifiers into system-friendly entity or variable names
            LayerName: STARK_friendly_to_system_name
            CompatibleArchitectures:
                - x86_64
                - arm64
            CompatibleRuntimes:
                - python3.6
                - python3.7
                - python3.8
                - python3.9
    STARKScryptLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: !Ref UserCodeGenBucketNameParameter
                S3Key: STARKLambdaLayers/STARK_scrypt_py39.zip
            Description: STARK module for working with scrypt from the Python stdlib
            LayerName: STARK_scrypt
            CompatibleArchitectures:
                - x86_64
                - arm64
            CompatibleRuntimes:
                - python3.6
                - python3.7
                - python3.8
                - python3.9
    STARKGetRelationshipLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: !Ref UserCodeGenBucketNameParameter
                S3Key: STARKLambdaLayers/STARK_get_relationship_py39.zip
            Description: STARK helper function for extracting relationship for 1-1 and 1-Many for business modules
            LayerName: STARK_get_relationship
            CompatibleArchitectures:
                - x86_64
                - arm64
            CompatibleRuntimes:
                - python3.6
                - python3.7
                - python3.8
                - python3.9
    STARKSuggestGraphicLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Content:
                S3Bucket: !Ref UserCodeGenBucketNameParameter
                S3Key: STARKLambdaLayers/STARK_suggest_graphic_py39.zip
            Description: STARK module for assigning suggested icons
            LayerName: STARK_suggest_graphic
            CompatibleArchitectures:
                - x86_64
                - arm64
            CompatibleRuntimes:
                - python3.6
                - python3.7
                - python3.8
                - python3.9
    STARKParserFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /parser
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_Parser
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
                - !Ref STARKGetRelationshipLayer
                - !Ref STARKScryptLayer
            Timeout: 60 
            Architectures:
                - arm64
    STARKCFWriterFunc:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_CFWriter
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AmazonS3FullAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 60
            Architectures:
                - arm64
    STARKDeployFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /deploy
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_Deploy
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AWSLambda_FullAccess
                - AWSCloudFormationFullAccess
                - IAMFullAccess
                - AmazonS3ReadOnlyAccess
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 600
            Architectures:
                - arm64
    STARKDeployCheckFunc:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ParserPostEvent:
                    Type: HttpApi
                    Properties:
                        Path: /deploy_check
                        Method: POST
                        ApiId:
                            Ref: STARKParserApi
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_Deploy_Check
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
            Policies:
                - AWSLambda_FullAccess
                - AWSCloudFormationFullAccess
                - AmazonS3ReadOnlyAccess
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 600
            Architectures:
                - arm64
    STARKCodeGenStaticWriter:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_CodeGen_Static
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AmazonS3FullAccess
                - AWSLambdaBasicExecutionRole
                - AWSCodeCommitFullAccess
                - AWSCodePipeline_FullAccess
                - ReadOnlyAccess
                - IAMFullAccess
            Layers:
                - !Ref CFCustomResourceHelperLayer
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
                - !Ref STARKGetRelationshipLayer
            Timeout: 60
            Architectures:
                - arm64
    STARKCodeGenStaticWriterV2:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_CodeGen_StaticV2
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AmazonS3FullAccess
                - AWSLambdaBasicExecutionRole
                - AWSCodeCommitFullAccess
                - AWSCodePipeline_FullAccess
                - ReadOnlyAccess
                - IAMFullAccess
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
                - !Ref STARKGetRelationshipLayer
            Timeout: 60
            Architectures:
                - arm64
    STARKCodeGenDynamicWriter:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_CodeGen_Dynamic
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AmazonS3FullAccess
                - AWSLambda_FullAccess 
                - AWSCodeCommitFullAccess
                - AWSCodePipeline_FullAccess
                - IAMFullAccess
            Layers:
                - !Ref CFCustomResourceHelperLayer
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
                - !Ref STARKGetRelationshipLayer
                - !Ref STARKSuggestGraphicLayer
            Timeout: 60
            Architectures:
                - arm64
    STARKCodeGenDynamicWriterV2:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_CodeGen_DynamicV2
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AmazonS3FullAccess
                - AWSLambda_FullAccess 
                - AWSCodeCommitFullAccess
                - AWSCodePipeline_FullAccess
                - IAMFullAccess
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
                - !Ref STARKGetRelationshipLayer
                - !Ref STARKSuggestGraphicLayer
            Timeout: 60
            Architectures:
                - arm64
    STARKBucketCleanerFunc:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_WebsiteBucketCleaner
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
            Policies:
                - AmazonS3FullAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - !Ref CFCustomResourceHelperLayer
            Timeout: 60
            Architectures:
                - arm64
    STARKSystemBootstrap:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_SystemBootstrap
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AmazonS3FullAccess
                - AWSLambdaBasicExecutionRole
                - AWSCodeCommitFullAccess
            Layers:
                - !Ref CFCustomResourceHelperLayer
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
            Timeout: 60
            Architectures:
                - arm64
    STARKSystemPreLaunch:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_SystemPreLaunch
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AWSLambdaBasicExecutionRole
                - AWSCodeCommitFullAccess
                - AmazonDynamoDBFullAccess
                - AmazonS3FullAccess
            Layers:
                - !Ref CFCustomResourceHelperLayer
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
                - !Ref STARKSuggestGraphicLayer
                - !Ref STARKGetRelationshipLayer
            Architectures:
                - arm64
            MemorySize: 1760
            Timeout: 60
    STARKSystemPreLaunchV2:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_SystemPreLaunchV2
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
            Policies:
                - AWSLambdaBasicExecutionRole
                - AWSCodeCommitFullAccess
                - AmazonDynamoDBFullAccess
                - AmazonS3FullAccess
            Layers:
                - !Ref PyYamlLayer
                - !Ref STARKFriendlyToSystemNamesLayer
                - !Ref STARKSuggestGraphicLayer
                - !Ref STARKGetRelationshipLayer
                - !Ref PymongoLayer
            Architectures:
                - arm64
            MemorySize: 1760
            Timeout: 60
    STARKWebsiteUpdaterFunc:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_WebsiteUpdater
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
                    WEBSITE_BUCKET_NAME: !Ref UserWebsiteBucketNameParameter
                    API_GATEWAY_ID: !Ref STARKParserApi
            Policies:
                - AmazonS3FullAccess
                - AWSLambdaBasicExecutionRole
                - ReadOnlyAccess
            Layers:
                - !Ref CFCustomResourceHelperLayer
            Timeout: 60
            Architectures:
                - arm64
    STARKWebsiteUpdaterRun:
        Type: AWS::CloudFormation::CustomResource
        Properties:
            ServiceToken: !GetAtt STARKWebsiteUpdaterFunc.Arn
            ApiGatewayId: !Ref STARKParserApi
            UpdateToken: RandomTokenFromBuildScript
            Remarks: This will update STARK_settings.js with the appropriate API Gateway ID
        DependsOn:
            -   STARKParserApi
            -   STARKWebsiteUpdaterFunc
    STARKConfigWriterFunc:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: python3.9
            Handler: __init__.lambda_handler
            CodeUri: lambda/STARK_ConfigWriter
            Environment:
                Variables:
                    STARK_ENVIRONMENT_TYPE: PROD
                    CODEGEN_BUCKET_NAME: !Ref UserCodeGenBucketNameParameter
                    CICD_BUCKET_NAME: !Ref UserCICDPipelineBucketNameParameter
                    API_GATEWAY_ID: !Ref STARKParserApi
                    CLEANER_ARN: !GetAtt STARKBucketCleanerFunc.Arn
                    CF_WRITER_ARN: !GetAtt STARKCFWriterFunc.Arn
                    CG_DYNAMIC_ARN: !GetAtt STARKCodeGenDynamicWriter.Arn
                    CG_DYNAMICV2_ARN: !GetAtt STARKCodeGenDynamicWriterV2.Arn
                    CG_STATIC_ARN: !GetAtt STARKCodeGenStaticWriter.Arn
                    CG_STATICV2_ARN: !GetAtt STARKCodeGenStaticWriterV2.Arn
                    CF_DEPLOY_ROLE_ARN: !GetAtt STARKCloudFormationDeployServiceRole.Arn
                    SYSTEM_BOOTSTRAP_ARN: !GetAtt STARKSystemBootstrap.Arn
                    SYSTEM_PRELAUNCH_ARN: !GetAtt STARKSystemPreLaunch.Arn
                    SYSTEM_PRELAUNCHV2_ARN: !GetAtt STARKSystemPreLaunchV2.Arn
            Policies:
                - AmazonS3FullAccess
                - AWSLambdaBasicExecutionRole
            Layers:
                - !Ref CFCustomResourceHelperLayer
            Timeout: 60
            Architectures:
                - arm64
    STARKConfigWriterRun:
        Type: AWS::CloudFormation::CustomResource
        Properties:
            ServiceToken: !GetAtt STARKConfigWriterFunc.Arn
            UpdateToken: RandomTokenFromBuildScript
            Remarks: This will update STARK_settings.js with the appropriate API Gateway ID
        DependsOn:
            -   STARKConfigWriterFunc